language: php

php:
  - 5.6
  - 7.0

before_script:
  - cp .env.example .env
  - touch database/database.sqlite
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate

script:
  - vendor/bin/phpunit